### ISSUE TITLE
Support for JDK 11+

### ISSUE THREAD

**Issue by d3athwarrior** [davidmoten/grumpy#8]
I tried to use this library in an environment where JDK 11 is used and it starts to give below mentioned error with respect to the rendering library:
```
java.lang.IllegalArgumentException: org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class
	at java.desktop/javax.imageio.spi.ServiceRegistry.checkClassAllowed(ServiceRegistry.java:722)
	at java.desktop/javax.imageio.spi.ServiceRegistry.<init>(ServiceRegistry.java:117)
	at org.geotools.factory.FactoryRegistry.<init>(FactoryRegistry.java:155)
	at org.geotools.factory.FactoryRegistry.<init>(FactoryRegistry.java:146)
	at org.geotools.factory.FactoryCreator.<init>(FactoryCreator.java:82)
	at org.geotools.referencing.ReferencingFactoryFinder.getServiceRegistry(ReferencingFactoryFinder.java:115)
	at org.geotools.referencing.ReferencingFactoryFinder.getFactories(ReferencingFactoryFinder.java:180)
	at org.geotools.referencing.ReferencingFactoryFinder.getCRSAuthorityFactories(ReferencingFactoryFinder.java:455)
	at org.geotools.referencing.DefaultAuthorityFactory.getBackingFactory(DefaultAuthorityFactory.java:88)
	at org.geotools.referencing.DefaultAuthorityFactory.<init>(DefaultAuthorityFactory.java:69)
	at org.geotools.referencing.CRS.getAuthorityFactory(CRS.java:262)
	at org.geotools.referencing.CRS.decode(CRS.java:519)
	at org.geotools.referencing.CRS.decode(CRS.java:447)
	at com.github.davidmoten.grumpy.projection.FeatureUtil.getCrs(FeatureUtil.java:47)
	at com.github.davidmoten.grumpy.wms.WmsUtil.getScale(WmsUtil.java:50)
	at com.se.datex2clienttoolkit.controllers.CustomLayer.render(CustomLayer.java:63)
	at com.github.davidmoten.grumpy.wms.LayerManager.paintLayer(LayerManager.java:167)
	at com.github.davidmoten.grumpy.wms.LayerManager.access$100(LayerManager.java:24)
	at com.github.davidmoten.grumpy.wms.LayerManager$2.call(LayerManager.java:150)
	at com.github.davidmoten.grumpy.wms.LayerManager$2.call(LayerManager.java:145)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-12-01 10:13:51,979 [http-nio-8080-exec-6] ERROR c.g.d.grumpy.wms.LayerManager - java.lang.IllegalArgumentException: org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.github.davidmoten.grumpy.wms.LayerManager.drawImage(LayerManager.java:175)
	at com.github.davidmoten.grumpy.wms.LayerManager.paintImageParallel(LayerManager.java:139)
	at com.github.davidmoten.grumpy.wms.LayerManager.paintImage(LayerManager.java:113)
	at com.github.davidmoten.grumpy.wms.LayerManager.getImage(LayerManager.java:49)
	at com.github.davidmoten.grumpy.wms.WmsServletRequestProcessor.writeImage(WmsServletRequestProcessor.java:212)
	at com.github.davidmoten.grumpy.wms.WmsServletRequestProcessor.doGet(WmsServletRequestProcessor.java:144)
	at com.se.datex2clienttoolkit.controllers.WMSController.wmsRequestProcessor(WMSController.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:807)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1061)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:961)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.se.datex2clienttoolkit.filters.RequestLoggingFilter.doFilter(RequestLoggingFilter.java:28)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class
	at java.desktop/javax.imageio.spi.ServiceRegistry.checkClassAllowed(ServiceRegistry.java:722)
	at java.desktop/javax.imageio.spi.ServiceRegistry.<init>(ServiceRegistry.java:117)
	at org.geotools.factory.FactoryRegistry.<init>(FactoryRegistry.java:155)
	at org.geotools.factory.FactoryRegistry.<init>(FactoryRegistry.java:146)
	at org.geotools.factory.FactoryCreator.<init>(FactoryCreator.java:82)
	at org.geotools.referencing.ReferencingFactoryFinder.getServiceRegistry(ReferencingFactoryFinder.java:115)
	at org.geotools.referencing.ReferencingFactoryFinder.getFactories(ReferencingFactoryFinder.java:180)
	at org.geotools.referencing.ReferencingFactoryFinder.getCRSAuthorityFactories(ReferencingFactoryFinder.java:455)
	at org.geotools.referencing.DefaultAuthorityFactory.getBackingFactory(DefaultAuthorityFactory.java:88)
	at org.geotools.referencing.DefaultAuthorityFactory.<init>(DefaultAuthorityFactory.java:69)
	at org.geotools.referencing.CRS.getAuthorityFactory(CRS.java:262)
	at org.geotools.referencing.CRS.decode(CRS.java:519)
	at org.geotools.referencing.CRS.decode(CRS.java:447)
	at com.github.davidmoten.grumpy.projection.FeatureUtil.getCrs(FeatureUtil.java:47)
	at com.github.davidmoten.grumpy.wms.WmsUtil.getScale(WmsUtil.java:50)
	at com.se.datex2clienttoolkit.controllers.CustomLayer.render(CustomLayer.java:63)
	at com.github.davidmoten.grumpy.wms.LayerManager.paintLayer(LayerManager.java:167)
	at com.github.davidmoten.grumpy.wms.LayerManager.access$100(LayerManager.java:24)
	at com.github.davidmoten.grumpy.wms.LayerManager$2.call(LayerManager.java:150)
	at com.github.davidmoten.grumpy.wms.LayerManager$2.call(LayerManager.java:145)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 common frames omitted
```

I updated the geotools library and the above error was gone, instead I started to see more errors for duplicate and that was due to the following library being used:
[`com.vividsolutions:jts-core`](https://mvnrepository.com/artifact/com.vividsolutions/jts-core) - This has now moved to a different group on maven central and geotools also uses the new library which is
[`org.locationtech.jts:jts-core`](https://mvnrepository.com/artifact/org.locationtech.jts/jts-core)

This is essentially rendering the project useless if I want to use it directly as a library.

Edit1: Updated the stack trace to be inside a multiline code block

**Comment by davidmoten** [comment]
Thanks for the report, would you be able to submit a PR to fix?

**Comment by d3athwarrior** [comment]
@davidmoten Sure. I hadn't fixed everything on here but yes I could try to fix and submit a PR once everything builds fine.

**Comment by d3athwarrior** [comment]
Hi,
I have opened a PR https://github.com/davidmoten/grumpy/pull/9

Please have a look and let me know in case you have any concerns over it

**Comment by d3athwarrior** [comment]
Hi @davidmoten 
Closing this Issue since the PR https://github.com/davidmoten/grumpy/pull/9 has been merged and issue is not replicated on the latest version released on maven central.
